spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plenti_db
    username: your_username
    password: TechBro77@$
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
    password: your_redis_password

jwt:
  secret: your_jwt_secret_key
  expiration: 3600 # 1 hour in seconds

monnify:
  api-key: your_monnify_api_key
  secret-key: your_monnify_secret_key
